import { Client, Connection } from '@temporalio/client';
import { msnArticleGeneratorWorkflow } from './workflows';
import type { FormInput } from './types';
import * as dotenv from 'dotenv';

dotenv.config();

async function triggerWorkflow(input: FormInput): Promise<void> {
  const connection = await Connection.connect({ address: 'localhost:7233' });
  const client     = new Client({ connection });

  const handle = await client.workflow.start(msnArticleGeneratorWorkflow, {
    taskQueue:  'msn-article-generator',
    workflowId: `msn-article-${Date.now()}`,
    args:       [input],
  });

  console.log(`Workflow started: ${handle.workflowId}`);
  console.log(`Temporal UI: http://localhost:8233/namespaces/default/workflows/${handle.workflowId}`);

  const result = await handle.result();
  console.log('\n=== WORKFLOW COMPLETE ===');
  console.log(`Quality Score:    ${result.qualityScore}/100`);
  console.log(`Generated by:     ${result.generatedBy}`);
  console.log(`Slides:           ${result.slides.length}`);
  console.log(`Flags for review: ${result.flagsForReview}`);
  console.log(`Summary:          ${result.summaryComment}`);
}

// ── Example trigger – edit the input and run: npm run trigger ─────────────────

const exampleInput: FormInput = {
  writerName:       'Sarah Johnson',
  title:            '20 NFL Quarterbacks Who Dominated the 2025 Season',
  category:         'Sports - NFL',
  slideCount:       20,
  slidesPerEntityRaw: '1 (Standard)',
  sourcesRaw:       '',
  mustIncludeRaw:   '',
  userContext:      '',
  writingStyle:     'casual and punchy, short lines',
};

triggerWorkflow(exampleInput).catch(err => {
  console.error('Failed to trigger workflow:', err);
  process.exit(1);
});
